version: '3.8'

services:
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes: 
      - .:/app
    restart: always
    depends_on:
      - db
    env_file:
      - .env

  queue:
    build: .
    command: 'python consumer.py'
    volumes: 
      - .:/app
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data/
    restart: always

volumes:
  dbdata: